# Generated by Django 3.1.2 on 2022-01-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_name',
            name='site_fevicon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='app_name',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
