# Generated by Django 3.1.2 on 2022-01-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220126_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App_Name',
            new_name='AppName',
        ),
    ]
