# Generated by Django 4.0.1 on 2022-01-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_appname_id_alter_appname_site_fevicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appname',
            name='site_fevicon',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='appname',
            name='site_logo',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
