# Generated by Django 4.0.1 on 2022-01-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_appname_site_fevicon_alter_appname_site_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=150)),
                ('app_version', models.FloatField()),
                ('app_logo', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('app_fevicon', models.FileField(blank=True, null=True, upload_to='upload/')),
            ],
        ),
        migrations.DeleteModel(
            name='AppName',
        ),
    ]
